### ISSUE TITLE
V1.6.6 broken  mode and show type dropdowns revert to wrong value and cannot be saved

### ISSUE THREAD

**Issue by raymondjstone** [BiglySoftware/BiglyBT-plugin-rssfeed#1]
in the filterbeans, mode is set as fail before update, reverts to pass and cannot be saved back to fail, it can be selected on the dropdown as fail but it always ends up saved as pass again

type field has a similar issue with tvshow being the default for everything (which mine were anyway)

**Comment by raymondjstone** [comment]
BTW 1.6.6 was installed as part of the upgrade to BiglyBT 1.5.0.0 which updated itself this morning, everything was fine until that point, but I can't seem to get the old version of rssfeed working now either, same issue

**Comment by parg** [comment]
Please update to 1.6.7 and see if that fixes things

**Comment by raymondjstone** [comment]
Nope same issue,

For testing I deleted the options file and let it create a new add, added in two filters, went and tried to change one to 'fail' but it always remains as pass when saved

**Comment by parg** [comment]
Very odd - 1.6.7. definitely fixes the mode saving bug for me :(

**Comment by raymondjstone** [comment]
I have tried it again both using the options file from 1.6.6 and creating a new one under 1.6.7

create two filters both set to pass
go back and edit one to Fail and click save
Filters list still shows pass and if you leave the current item and then go back to it it reverts to pass

![2018-04-12 10_34_03-biglybt](https://user-images.githubusercontent.com/9839266/38668983-1c6710ac-3e3d-11e8-8ea3-beccb4b0a56b.png)

**Comment by raymondjstone** [comment]
![2018-04-12 10_36_07-options](https://user-images.githubusercontent.com/9839266/38669078-562cfaea-3e3d-11e8-8808-2ae762d8b635.png)

**Comment by raymondjstone** [comment]
Also just tried creating a new item with FAIL as the initial value, gets saves as PASS

**Comment by raymondjstone** [comment]
Some further testing, FAIL works if NOT TV Show but when I switch the item back to that it reverts to pass all the time

**Comment by raymondjstone** [comment]
actually change that, it only works when it is the corrupted movie value reported on the linked thread
![2018-04-12 11_35_32-biglybt](https://user-images.githubusercontent.com/9839266/38672287-a25d7694-3e45-11e8-9c80-41b7769725bb.png)

**Comment by raymondjstone** [comment]
If I change it to movie and fail then save then change it to other this happens, (and it ends up as pass when you leave the item and go back in)
![2018-04-12 11_36_40-biglybt](https://user-images.githubusercontent.com/9839266/38672371-e11ccd1c-3e45-11e8-8756-cef9b2c58e4e.png)

**Comment by raymondjstone** [comment]
The JSON extract is also broken, I assume by the same issue

As per screen print 3 items in the filterbeans, however on the json extract despite one being 'FAIL' the mode is always exported as 1.
![2018-04-12 12_47_02-biglybt](https://user-images.githubusercontent.com/9839266/38675486-cdc0c5ca-3e4f-11e8-824f-cec278a9e503.png)


{
  "@type":"org.kmallan.azureus.rssfeed.Config$JSONWrapper",
  "urlBeans":{
    "@id":28,
    "@type":"java.util.ArrayList",
    "@items":[
      {
        "@id":30,
        "@type":"org.kmallan.azureus.rssfeed.UrlBean",
        "name":"New Item",
        "location":"xdxxx",
        "storeDir":"",
        "referer":"",
        "cookie":"",
        "urlId":1523529175967,
        "obeyTTL":true,
        "locReferer":true,
        "useCookie":false,
        "enabled":false,
        "delay":0,
        "prevBackLogSize":0,
        "backLog":null
      }
    ]
  },
  "filterBeans":{
    "@id":4,
    "@type":"java.util.ArrayList",
    "@items":[
      {
        "@id":20,
        "@type":"org.kmallan.azureus.rssfeed.FilterBean",
        "name":"New Itemsd",
        "storeDir":"",
        "expression":"",
        "exclude":"",
        "category":"",
        "type":"0",
        "mode":"1",
        "excludes":{
          "@type":"java.util.ArrayList"
        },
        "state":0,
        "rateUpload":0,
        "rateDownload":0,
        "startSeason":0,
        "startEpisode":0,
        "endSeason":0,
        "endEpisode":0,
        "filtId":1523525511147,
        "urlId":1523529175967,
        "isRegex":false,
        "isFilename":false,
        "matchTitle":true,
        "matchLink":true,
        "moveTop":false,
        "customRate":false,
        "renameFile":false,
        "renameIncEpisode":false,
        "disableAfter":false,
        "cleanFile":false,
        "enabled":false,
        "smartHistory":true,
        "exprLower":"",
        "exprPat":{
          "pattern":".*.*",
          "flags":0
        },
        "minTorrentSize":0,
        "maxTorrentSize":0
      },
      {
        "@id":9,
        "@type":"org.kmallan.azureus.rssfeed.FilterBean",
        "name":"New Item3",
        "storeDir":"",
        "expression":"",
        "exclude":"",
        "category":"",
        "type":"1",
        "mode":"1",
        "excludes":{
          "@type":"java.util.ArrayList"
        },
        "state":0,
        "rateUpload":0,
        "rateDownload":0,
        "startSeason":0,
        "startEpisode":0,
        "endSeason":0,
        "endEpisode":0,
        "filtId":1523527939452,
        "urlId":1523529175967,
        "isRegex":false,
        "isFilename":false,
        "matchTitle":true,
        "matchLink":true,
        "moveTop":false,
        "customRate":false,
        "renameFile":false,
        "renameIncEpisode":false,
        "disableAfter":false,
        "cleanFile":false,
        "enabled":true,
        "smartHistory":true,
        "exprLower":"",
        "exprPat":{
          "pattern":".*.*",
          "flags":0
        },
        "minTorrentSize":0,
        "maxTorrentSize":0
      },
      {
        "@id":6,
        "@type":"org.kmallan.azureus.rssfeed.FilterBean",
        "name":"New Item",
        "storeDir":"",
        "expression":"",
        "exclude":"",
        "category":"",
        "type":"0",
        "mode":"1",
        "excludes":{
          "@type":"java.util.ArrayList"
        },
        "state":0,
        "rateUpload":0,
        "rateDownload":0,
        "startSeason":0,
        "startEpisode":0,
        "endSeason":0,
        "endEpisode":0,
        "filtId":1523525503646,
        "urlId":0,
        "isRegex":false,
        "isFilename":false,
        "matchTitle":true,
        "matchLink":true,
        "moveTop":false,
        "customRate":false,
        "renameFile":false,
        "renameIncEpisode":false,
        "disableAfter":false,
        "cleanFile":false,
        "enabled":false,
        "smartHistory":true,
        "exprLower":"",
        "exprPat":{
          "pattern":".*.*",
          "flags":0
        },
        "minTorrentSize":0,
        "maxTorrentSize":0
      }
    ]
  },
  "historyBeans":{
    "@id":2,
    "@type":"java.util.ArrayList"
  }
}

**Comment by raymondjstone** [comment]
While deleting stuff from the plugins directory I noticed that the 1.6.6 jar was still being used despite the install of 1.6.7 and multiple restarts. I shut down  the app but a background process was remaining and keeping the wrong jar loaded. killed that and now 1.6.7 is mostly working, mode shows as blank not fail but it does keep the setting 
![2018-04-12 12_59_26-biglybt](https://user-images.githubusercontent.com/9839266/38676000-8d1cc5d0-3e51-11e8-9365-62ba6cfb7e11.png)

**Comment by raymondjstone** [comment]
Not sure about the JSON now, will need to retest that but to get the filters working correctly I reset the app to use a backup taken before 1.6.6 was installed and that seems to have opened ok now in 1.6.7. I originally tried importing back from a JSON backup but that did not work but it could be that I changed the mode within the JSON from fail to the wrong int value,

**Comment by parg** [comment]
Sorry, been away for the last couple of days - how are things? The issue before the change that broke things with 1.6.6 is that some of the values (mode and type) were being saved as localised string values - this worked with 'en' but was borked when people switched their client locale (things were then saved under the new locale's strings but other bits of the code were assuming 'en' and testing against this. I switched things to use indexes but messed up one of the changes (for mode)

**Comment by raymondjstone** [comment]
The original settings file that had been used in 1.6.6 was not easily fixed so I reverted back to a backup and used 1.6.7 on that and it was fine and has been working perfectly today.

**Comment by parg** [comment]
great!

**Comment by n1diot** [comment]
For this user having issues with the "FAIL" can I suggest using "EXCLUDE" as it works for me.

Though after reading the posts, seems that it is working?

![image](https://user-images.githubusercontent.com/34951705/39390903-ec8d232c-4ade-11e8-97d3-d1623d2159e0.png)
