### ISSUE TITLE
Dark Mode and the RSSFeed help text...

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT-plugin-rssfeed#8]
@parg @TuxPaper 

So, on the topic of "BiglyBT... _After Dark_", the RSSFeed Scanner help tab looks kuh-raaaayze! (See below.)

Now, I know the implementation there is... Special™ — **inventing your own markup language** is, after all, the obvious approach to displaying some help text — so I wouldn't be cruel enough to send anyone down the road of working on that nonsense. So here's what I was thinking:

Say I were to re-do the help texts themselves in HTML, like a person living in the 21st Century. (Both the English and French, why not? I don't have to _understand_ it to format it.) And say I were to submit that in a PR. Would it be easy enough for one of you smack that `StyledText` subclass out of there (["IMPORTANT: This class is _not_ intended to be subclassed."](https://javadoc.scijava.org/Eclipse/org/eclipse/swt/custom/StyledText.html)), and replace it with an embedded browser instance, like the Beta Program view? (But loading from a local resource, instead of over the net.)

I could probably work that code out eventually, but it'd take me a week and it would probably still suck. (Though, considering what it'd be replacing... :roll_eyes: )

![Screenshot from 2021-12-30 07-54-36](https://user-images.githubusercontent.com/538020/147755999-9007c4a7-6e82-4f74-ac52-f01c357021e3.png)

**Comment by ferdnyc** [comment]
(Among the many advantages in switching to HTML would be the ability to use real headings and bullet lists, with wrapped paragraphs that actually line up on their left indents. `StyledText` can do that, too — it has `setLineBullet()` and `setLineWrapIndent()` — but the code doesn't use those. Instead, it fakes the indents by prepending spaces to the text. So you end up with stuff like this...)

![image](https://user-images.githubusercontent.com/538020/147795442-28c71a3b-758c-4981-9e32-628826fed0e0.png)

**Comment by parg** [comment]
I think if I do anything I'll just make everything white-on-black in dark mode :)

**Comment by ferdnyc** [comment]
@parg FEH. I was worried you were going to say that. The wrapping will still look like ass, though! And the bullets will still be  asterisks just randomly stuck before the text. And... and... the headings! That aren't headings!

HTML can solve all of these things. It's almost like it was _created_ for the purpose of applying semantic markup to text, or something.

...Still, even that would be a vast improvement over the current nonsense, so that works for me. (Plus, it should be as easy as just _removing_ all of the foreground and background changes from the code. The tab clearly _defaults_ to the theme colors initially, until it gets "styled" into oblivion.)

**Comment by ferdnyc** [comment]
Fixed! \o/

![Screenshot from 2022-01-02 18-32-30](https://user-images.githubusercontent.com/538020/147892264-7b6bb98e-6aba-4fb6-9546-72c9d9fb4dbb.png)
